-- Pimary form logic questions
INSERT INTO `logic_combinations` (`id`,`form_id`, `question_id`, `ans_ids`, `comb_json`) VALUES (1,'2', '1', '1', '[{"question_id": 104, "on_option_id":[]}]');
INSERT INTO `logic_combinations` (`id`,`form_id`, `question_id`, `ans_ids`, `comb_json`) VALUES (2,'2', '1', '2', '[{"question_id": 105, "on_option_id":[{"id": 621, "question_id": 104, "on_option_id":[]}]}]');
INSERT INTO `logic_combinations` (`id`,`form_id`, `question_id`, `ans_ids`, `comb_json`) VALUES (3,'2', '1', '3', '[{"question_id": 106, "on_option_id":[]}]');
INSERT INTO `logic_combinations` (`id`,`form_id`, `question_id`, `ans_ids`, `comb_json`) VALUES (4,'2', '1', '4', '[{"question_id": 105, "on_option_id":[{"id": 621, "question_id": 104, "on_option_id":[]}]}]');
INSERT INTO `logic_combinations` (`id`,`form_id`, `question_id`, `ans_ids`, `comb_json`) VALUES (5,'2', '1', '1,2', '[{"question_id": 105, "on_option_id":[{"id": 621, "question_id": 104, "on_option_id":[]}]}]');
INSERT INTO `logic_combinations` (`id`,`form_id`, `question_id`, `ans_ids`, `comb_json`) VALUES (6,'2', '1', '1,3', '[{"question_id": 104, "on_option_id":[]}, {"question_id": 106, "on_option_id": []}]');
INSERT INTO `logic_combinations` (`id`,`form_id`, `question_id`, `ans_ids`, `comb_json`) VALUES (7,'2', '1', '1,4', '[{"question_id": 104, "on_option_id":[]}]');
INSERT INTO `logic_combinations` (`id`,`form_id`, `question_id`, `ans_ids`, `comb_json`) VALUES (8,'2', '1', '2,3', '[{"question_id": 105, "on_option_id":[{"id": 621, "question_id": 104, "on_option_id":[{"id": 619, "question_id": 106, "on_option_id":[]},{"id": 620, "question_id": 106, "on_option_id":[]}]},{"id": 622, "question_id": 106, "on_option_id":[]}]}]');
INSERT INTO `logic_combinations` (`id`,`form_id`, `question_id`, `ans_ids`, `comb_json`) VALUES (9,'2', '1', '2,4', '[{"question_id": 105, "on_option_id":[{"id": 621, "question_id": 104, "on_option_id":[]}]}]');
INSERT INTO `logic_combinations` (`id`,`form_id`, `question_id`, `ans_ids`, `comb_json`) VALUES (10,'2', '1', '3,4', '[{"question_id": 105, "on_option_id":[{"id": 621, "question_id": 104, "on_option_id":[{"id": 619, "question_id": 106, "on_option_id":[]},{"id": 620, "question_id": 106, "on_option_id":[]}]},{"id": 622, "question_id": 106, "on_option_id":[]}]}]');
INSERT INTO `logic_combinations` (`id`,`form_id`, `question_id`, `ans_ids`, `comb_json`) VALUES (11,'2', '1', '1,2,3', '[{"question_id": 104, "on_option_id":[]}, {"question_id": 106, "on_option_id":[]}]');
INSERT INTO `logic_combinations` (`id`,`form_id`, `question_id`, `ans_ids`, `comb_json`) VALUES (12,'2', '1', '1,2,4', '[{"question_id": 104, "on_option_id":[]}]');
INSERT INTO `logic_combinations` (`id`,`form_id`, `question_id`, `ans_ids`, `comb_json`) VALUES (13,'2', '1', '1,3,4', '[{"question_id": 104, "on_option_id":[]}, {"question_id": 106, "on_option_id":[]}]');
INSERT INTO `logic_combinations` (`id`,`form_id`, `question_id`, `ans_ids`, `comb_json`) VALUES (14,'2', '1', '2,3,17', '[{"question_id": 105, "on_option_id":[{"id": 621, "question_id": 104, "on_option_id":[{"id": 619, "question_id": 106, "on_option_id":[]},{"id": 620, "question_id": 106, "on_option_id":[]}]},{"id": 622, "question_id": 106, "on_option_id":[]}]}]');
INSERT INTO `logic_combinations` (`id`,`form_id`, `question_id`, `ans_ids`, `comb_json`) VALUES (15,'2', '1', '1,2,3,4', '[{"question_id": 104, "on_option_id":[]}, {"question_id": 106, "on_option_id":[]}]');
INSERT INTO `logic_combinations` (`id`,`form_id`, `question_id`, `ans_ids`, `comb_json`) VALUES (16,'2', '1', '2,3,4', '[{"question_id": 105, "on_option_id":[{"id": 621, "question_id": 104, "on_option_id":[{"id": 619, "question_id": 106, "on_option_id":[]},{"id": 620, "question_id": 106, "on_option_id":[]}]},{"id": 622, "question_id": 106, "on_option_id":[]}]}]');
-- Secondary form questions
INSERT INTO `logic_combinations` (`id`,`form_id`, `question_id`, `ans_ids`, `comb_json`) VALUES (17,'5', '1', '4', '[{"question_id": 15, "on_option_id":[]}, {"question_id": 16, "on_option_id":[]}, {"question_id": 17, "on_option_id":[]}, {"question_id": 18, "on_option_id":[]}, {"question_id": 19, "on_option_id":[]}, {"question_id": 20, "on_option_id":[]}, {"question_id": 21, "on_option_id":[]}, {"question_id": 22, "on_option_id":[]}, {"question_id": 23, "on_option_id":[]}, {"question_id": 24, "on_option_id":[]}, {"question_id": 25, "on_option_id":[]}, {"question_id": 26, "on_option_id":[]}, {"question_id": 27, "on_option_id":[]}, {"question_id": 28, "on_option_id":[]}, {"question_id": 29, "on_option_id":[]}, {"question_id": 30, "on_option_id":[]}]');
INSERT INTO `logic_combinations` (`id`,`form_id`, `question_id`, `ans_ids`, `comb_json`) VALUES (18,'5', '1', '3', '[{"question_id": 31, "on_option_id":[]}, {"question_id": 32, "on_option_id":[]}, {"question_id": 33, "on_option_id":[]}, {"question_id": 34, "on_option_id":[]}, {"question_id": 35, "on_option_id":[]}, {"question_id": 36, "on_option_id":[]}, {"question_id": 37, "on_option_id":[]}, {"question_id": 38, "on_option_id":[]}, {"question_id": 39, "on_option_id":[]}, {"question_id": 40, "on_option_id":[]}, {"question_id": 41, "on_option_id":[]}, {"question_id": 42, "on_option_id":[]}, {"question_id": 43, "on_option_id":[]}, {"question_id": 44, "on_option_id":[]}, {"question_id": 45, "on_option_id":[]}, {"question_id": 46, "on_option_id":[]},{"question_id": 47, "on_option_id":[]},{"question_id": 48, "on_option_id":[]},{"question_id": 49, "on_option_id":[]},{"question_id": 50, "on_option_id":[]},{"question_id": 51, "on_option_id":[]},{"question_id": 52, "on_option_id":[]},{"question_id": 53, "on_option_id":[]},{"question_id": 54, "on_option_id":[]},{"question_id": 55, "on_option_id":[]},{"question_id": 56, "on_option_id":[]},{"question_id": 57, "on_option_id":[]}]');
INSERT INTO `logic_combinations` (`id`,`form_id`, `question_id`, `ans_ids`, `comb_json`) VALUES (19,'5', '1', '1', '[{"question_id": 58, "on_option_id":[]}, {"question_id": 59, "on_option_id":[]}, {"question_id": 60, "on_option_id":[]}, {"question_id": 61, "on_option_id":[]}, {"question_id": 62, "on_option_id":[]}, {"question_id": 63, "on_option_id":[]}, {"question_id": 64, "on_option_id":[]}, {"question_id": 65, "on_option_id":[]}, {"question_id": 66, "on_option_id":[]}, {"question_id": 67, "on_option_id":[]}, {"question_id": 68, "on_option_id":[]}, {"question_id": 69, "on_option_id":[]}, {"question_id": 70, "on_option_id":[]}, {"question_id": 71, "on_option_id":[]}, {"question_id": 72, "on_option_id":[]}, {"question_id": 73, "on_option_id":[]}, {"question_id": 74, "on_option_id":[]}]');
INSERT INTO `logic_combinations` (`id`,`form_id`, `question_id`, `ans_ids`, `comb_json`) VALUES (20,'5', '1', '12', '[{"question_id": 75, "on_option_id":[]}, {"question_id": 76, "on_option_id":[]}, {"question_id": 77, "on_option_id":[]}, {"question_id": 78, "on_option_id":[]}, {"question_id": 79, "on_option_id":[]}, {"question_id": 80, "on_option_id":[]}, {"question_id": 81, "on_option_id":[]}, {"question_id": 82, "on_option_id":[]}, {"question_id": 83, "on_option_id":[]}, {"question_id": 84, "on_option_id":[]}, {"question_id": 85, "on_option_id":[]}, {"question_id": 86, "on_option_id":[]}, {"question_id": 87, "on_option_id":[]}, {"question_id": 88, "on_option_id":[]}]');
INSERT INTO `logic_combinations` (`id`,`form_id`, `question_id`, `ans_ids`, `comb_json`) VALUES (21,'5', '1', '13', '[{"question_id": 89, "on_option_id":[]}, {"question_id": 90, "on_option_id":[]}, {"question_id": 91, "on_option_id":[]}, {"question_id": 92, "on_option_id":[]}, {"question_id": 93, "on_option_id":[]}, {"question_id": 94, "on_option_id":[]}, {"question_id": 95, "on_option_id":[]}, {"question_id": 96, "on_option_id":[]}, {"question_id": 97, "on_option_id":[]}, {"question_id": 98, "on_option_id":[]}, {"question_id": 99, "on_option_id":[]}, {"question_id": 100, "on_option_id":[]}, {"question_id": 101, "on_option_id":[]}, {"question_id": 102, "on_option_id":[]}, {"question_id": 103, "on_option_id":[]}]');
-- Secondary form similar
INSERT INTO `logic_combinations` (`id`,`form_id`, `question_id`, `ans_ids`, `comb_json`, `parent_id`) VALUES (22,'5', '1', '2', '',17);
INSERT INTO `logic_combinations` (`id`,`form_id`, `question_id`, `ans_ids`, `comb_json`, `parent_id`) VALUES (23,'5', '1', '5', '',17);
INSERT INTO `logic_combinations` (`id`,`form_id`, `question_id`, `ans_ids`, `comb_json`, `parent_id`) VALUES (24,'5', '1', '6', '',17);
INSERT INTO `logic_combinations` (`id`,`form_id`, `question_id`, `ans_ids`, `comb_json`, `parent_id`) VALUES (25,'5', '1', '7', '',17);
INSERT INTO `logic_combinations` (`id`,`form_id`, `question_id`, `ans_ids`, `comb_json`, `parent_id`) VALUES (26,'5', '1', '8', '',17);
INSERT INTO `logic_combinations` (`id`,`form_id`, `question_id`, `ans_ids`, `comb_json`, `parent_id`) VALUES (27,'5', '1', '9', '',17);
INSERT INTO `logic_combinations` (`id`,`form_id`, `question_id`, `ans_ids`, `comb_json`, `parent_id`) VALUES (28,'5', '1', '10', '',17);
INSERT INTO `logic_combinations` (`id`,`form_id`, `question_id`, `ans_ids`, `comb_json`, `parent_id`) VALUES (29,'5', '1', '11', '',17);
INSERT INTO `logic_combinations` (`id`,`form_id`, `question_id`, `ans_ids`, `comb_json`, `parent_id`) VALUES (30,'5', '1', '14', '',17);